language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage codecov

script:
  - coverage run --source=./api manage.py test

after_success:
  - codecov -t fbcea2be-05b0-491e-b935-3364a6836d86
